<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD7cxx1U\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD7cxx1U/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD7cxx1U.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD7cxx1U\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerD7cxx1U\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'D7cxx1U',
    'container.build_id' => 'fb9f9209',
    'container.build_time' => 1650350367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD7cxx1U');
