<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'app_user_getusers' => [['search'], ['_controller' => 'App\\Controller\\UserController::getUsers'], ['search' => '[\\p{L}\\p{N}]*'], [['variable', '/', '[\\p{L}\\p{N}]*', 'search', true]], [], []],
];
