# docker-compose.yaml
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    tty: true
    depends_on:
      -   database
  #  environment:
  #    DATABASE_URL: postgresql://finportal:finportal@127.0.0.1:5432/finportal
    working_dir: /var/www
    volumes:
      - ./app:/var/www

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./app:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-finportal}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-finportal}
      POSTGRES_USER: ${POSTGRES_USER:-finportal}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db-data:
  db_data_test:
